{{- if not .Values.mariadb.auth.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appwrite.fullname" $ }}-db-env
  labels:
{{ include "appwrite.labels" $ | indent 4 }}
type: Opaque
data:
  _APP_DB_PASS: {{ .Values.mariadb.auth.password | b64enc }}
  _APP_DB_ROOT_PASS: {{ .Values.mariadb.auth.rootPassword | b64enc }}
{{- end }}
